# Generated by Django 4.2.11 on 2024-03-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='titlehere', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='slughere', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
