# Generated by Django 4.2.11 on 2024-03-06 14:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellnessblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('session_date_time', models.DateTimeField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('max_participants', models.IntegerField()),
                ('keywords', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-session_date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('STU', 'Student'), ('THE', 'Therapist'), ('INS', 'Instructor'), ('FOO', 'Food Vendor')], max_length=3)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('sessions_attended', models.ManyToManyField(related_name='attendees', to='wellnessblog.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(related_name='attended_sessions', to='wellnessblog.userprofile'),
        ),
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_provided', to='wellnessblog.userprofile'),
        ),
    ]
