# Generated by Django 4.2.11 on 2024-03-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellnessblog', '0002_session_userprofile_delete_blog_session_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_provided', to=settings.AUTH_USER_MODEL),
        ),
    ]
