# Generated by Django 4.2.11 on 2024-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessblog', '0004_alter_session_provider_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
