# Generated by Django 4.2.11 on 2024-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessblog', '0005_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='wellnessblog.userprofile'),
        ),
    ]
