# Generated by Django 4.2.11 on 2024-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessblog', '0006_alter_session_keywords_alter_session_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
