# Generated by Django 4.2.11 on 2024-03-06 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wellnessblog', '0007_alter_session_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('STU', 'Student'), ('THE', 'Therapist'), ('INS', 'Instructor'), ('FOO', 'Food Vendor')], max_length=300),
        ),
    ]
